### PR TITLE
init commit for issue #34

### PR DESCRIPTION
**Pull request by brodul**
Please take a look.
I will add a README.RST (how to install, uninstal) and prettify the code.

### CODE REVIEW

**Comment by brodul** [comment]
I suppose if the user want's to uninstall almir, he just has to kill all processes whose owner is almir and delete the install directory.

**Comment by domenkozar** [comment]
Thanks! Needs some cleaning, but very promising!

**Comment by brodul** [comment]
I think it just the readme.rst missing.

**Comment by brodul** [comment]
Done. Please review.

**Comment by brodul** [comment]
What's the status.  Should I do something?

**Comment by domenkozar** [comment]
First need to release 0.1.2 with some needed bugfixes, then I will work on 0.2 and merge this one.

**Comment by brodul** [comment]
k, tnx for feedback

**Comment by domenkozar** [comment]
Since almir is part of NixOS now, we don't need fabric anymore.

**Pull request closed without merging**
